// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://egqvfbisinhxldrzkphk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVncXZmYmlzaW5oeGxkcnprcGhrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwNTMwODMsImV4cCI6MjA2NDYyOTA4M30.VuplnjtNr3b5i3S7Z645zBxVTkhGHSo6iBHRfW0dOgQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);